---
http_interactions:
- request:
    method: post
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/retire
    body:
      encoding: UTF-8
      string: '{"ids":[203356]}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:26 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.072697'
      X-Request-Id:
      - e0c54776f8d2031672e73c6460472cac
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '201'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","moreInfo":[[{"id":203356,"externalId":"G75","status":"deprecated","sku":"O-3566","configuration":"INDIVIDUAL_ITEM","success":true},{"id":203357,"externalId":null,"status":"deprecated","sku":"A63","configuration":"MASTER_CASE","success":true}]],"resourceLocation":null}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:26 GMT
recorded_with: VCR 2.9.3
