---
http_interactions:
- request:
    method: put
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/202960
    body:
      encoding: UTF-8
      string: '[{"sku":"C27","externalId":"W-8134","description":"Super awesome description","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":0.1,"weight":0.1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0},"masterCase":{"individualItemsPerCase":1,"sku":"S-330","description":"Ampod
        HD Bridge","dimensions":{"length":1,"width":1,"height":1,"weight":1}},"inclusionRules":{"insertWhenWorthCurrency":"USD"},"classification":"marketingInsert"}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 09 Jun 2015 23:28:04 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.177417'
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '446'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/marketingInserts?offset=0&limit=1","resource":{"offset":0,"total":1,"previous":null,"next":null,"items":[{"resourceLocation":"https:\/\/api.beta.shipwire.com\/products\/marketingInserts\/202960","resource":{"id":202960,"externalId":"A-1769","sku":"X70","description":"Phuns
        Power Performance Adapter","inclusionRuleType":"MANUAL","creationDate":"2015-06-09T16:28:03-07:00","archivedDate":null,"status":"notinuse","storageConfiguration":"INDIVIDUAL_ITEM","classification":"marketingInsert","itemCount":1,"dimensions":{"resourceLocation":null},"alternateNames":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/products\/marketingInserts\/202960\/alternateNames?offset=0&limit=20"},"flags":{"resourceLocation":null},"inclusionRules":{"resourceLocation":null},"masterCase":{"resourceLocation":null}}}]}}'
    http_version: 
  recorded_at: Tue, 09 Jun 2015 23:28:04 GMT
recorded_with: VCR 2.9.3
