---
http_interactions:
- request:
    method: get
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/202960
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Tue, 09 Jun 2015 23:28:03 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.046697'
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '395'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/marketingInserts\/202960","resource":{"id":202960,"externalId":"A-1769","sku":"X70","description":"Phuns
        Power Performance Adapter","inclusionRuleType":"MANUAL","creationDate":"2015-06-09T16:28:03-07:00","archivedDate":null,"status":"notinuse","storageConfiguration":"INDIVIDUAL_ITEM","classification":"marketingInsert","itemCount":1,"dimensions":{"resourceLocation":null},"alternateNames":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/marketingInserts\/202960\/alternateNames?offset=0&limit=20"},"flags":{"resourceLocation":null},"inclusionRules":{"resourceLocation":null},"masterCase":{"resourceLocation":null}}}'
    http_version: 
  recorded_at: Tue, 09 Jun 2015 23:28:03 GMT
recorded_with: VCR 2.9.3
