---
http_interactions:
- request:
    method: put
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/510000014
    body:
      encoding: UTF-8
      string: '[{"sku":"Q-8781","externalId":"V-2093","description":"Aftersync Input
        Receiver","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":1,"weight":1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0},"virtualKitContent":[{"externalId":"TEST-PRODUCT","quantity":1},{"externalId":"TEST-PRODUCT2","quantity":1}],"classification":"virtualKit"}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:34 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.094549'
      X-Request-Id:
      - 5ba3f520ee1f5b8bb99cbb7c55cb3747
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '339'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/virtualKits?offset=0&limit=1","resource":{"offset":0,"total":1,"previous":null,"next":null,"items":[{"resourceLocation":"https:\/\/api.beta.shipwire.com\/products\/virtualKits\/510000014","resource":{"id":510000014,"externalId":"F32","sku":"F-5977","creationDate":"2015-06-22T09:30:32-07:00","description":"Phunt
        Side Controller","status":"instock","classification":"virtualKit","virtualKitContent":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/products\/virtualKits\/510000014\/content?offset=0&limit=20"},"flags":{"resourceLocation":null}}}]}}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:34 GMT
recorded_with: VCR 2.9.3
