---
http_interactions:
- request:
    method: get
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/203355
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:19 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.053935'
      X-Request-Id:
      - 5dfcb1862aa78fd3e5eb58f86172da3b
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '480'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/baseProducts\/203355","resource":{"id":203355,"externalId":"F34","sku":"H85","description":"Finpod
        Input GPS Component","hsCode":null,"countryOfOrigin":null,"creationDate":"2015-06-22T09:30:18-07:00","archivedDate":null,"status":"notinuse","storageConfiguration":"INDIVIDUAL_ITEM","batteryConfiguration":"NOBATTERY","classification":"baseProduct","category":"OTHER","itemCount":1,"vendorId":null,"vendorExternalId":null,"dimensions":{"resourceLocation":null},"values":{"resourceLocation":null},"alternateNames":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/baseProducts\/203355\/alternateNames?offset=0&limit=20"},"technicalData":{"resourceLocation":null},"flags":{"resourceLocation":null},"enqueuedDimensions":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/baseProducts\/203355\/enqueuedDimensions?offset=0&limit=20"},"innerPack":{"resourceLocation":null},"masterCase":{"resourceLocation":null},"pallet":{"resourceLocation":null}}}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:19 GMT
recorded_with: VCR 2.9.3
