---
http_interactions:
- request:
    method: put
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/0
    body:
      encoding: UTF-8
      string: '[{"sku":"L16","externalId":"I-7223","description":"Super awesome description","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":1,"weight":1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0},"classification":"baseProduct"}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Tue, 09 Jun 2015 23:28:00 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.026824'
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '88'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":404,"message":"Product not found.","resourceLocation":null}'
    http_version: 
  recorded_at: Tue, 09 Jun 2015 23:28:00 GMT
recorded_with: VCR 2.9.3
