---
http_interactions:
- request:
    method: post
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products
    body:
      encoding: UTF-8
      string: '[{"sku":"N78","externalId":"E-1357","description":"Trienswood Direct
        Remote Kit","classification":"fake","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":1,"weight":1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0}}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 400
      message: Bad Request
    headers:
      Date:
      - Mon, 22 Jun 2015 20:36:37 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.024903'
      X-Request-Id:
      - 756c2601321ce348b5d8251defd020e1
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '249'
      Connection:
      - close
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":400,"message":"Invalid request","errors":[{"message":"Product
        Classification not detected. Please pass classification for each product.","type":"error","code":400,"sku":"N78"}],"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products?offset=0&limit=0","resource":{"offset":0,"total":0,"previous":null,"next":null,"items":[]}}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 20:36:37 GMT
recorded_with: VCR 2.9.3
