---
http_interactions:
- request:
    method: post
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/retire
    body:
      encoding: UTF-8
      string: '{"ids":[203355]}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:21 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.107072'
      X-Request-Id:
      - 8c8b546c2c037403667c151f3e3b9208
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '171'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","moreInfo":[[{"id":203355,"externalId":"F34","status":"deprecated","sku":"H85","configuration":"INDIVIDUAL_ITEM","success":true}]],"resourceLocation":null}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:21 GMT
recorded_with: VCR 2.9.3
