---
http_interactions:
- request:
    method: get
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/203358
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:28 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.050585'
      X-Request-Id:
      - 0ed8d7fd179840caabd0796219f0f101
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '475'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/kits\/203358","resource":{"id":203358,"externalId":"K30","sku":"W59","description":"Troune
        Air System","hsCode":null,"countryOfOrigin":null,"creationDate":"2015-06-22T09:30:28-07:00","archivedDate":null,"status":"notinuse","storageConfiguration":"KIT","batteryConfiguration":"NOBATTERY","classification":"kit","category":"OTHER","itemCount":1,"vendorId":null,"vendorExternalId":null,"dimensions":{"resourceLocation":null},"values":{"resourceLocation":null},"alternateNames":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/kits\/203358\/alternateNames?offset=0&limit=20"},"kitContent":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/kits\/203358\/content?offset=0&limit=20"},"technicalData":{"resourceLocation":null},"flags":{"resourceLocation":null},"enqueuedDimensions":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/kits\/203358\/enqueuedDimensions?offset=0&limit=20"},"innerPack":{"resourceLocation":null},"masterCase":{"resourceLocation":null},"pallet":{"resourceLocation":null}}}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:28 GMT
recorded_with: VCR 2.9.3
