---
http_interactions:
- request:
    method: post
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/retire
    body:
      encoding: UTF-8
      string: '{"ids":[0]}'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Wed, 17 Jun 2015 23:30:32 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.028101'
      X-Request-Id:
      - a7c6580825e6ddabe11d9ece2ef5a7e3
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '79'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":null}'
    http_version: 
  recorded_at: Wed, 17 Jun 2015 23:30:32 GMT
recorded_with: VCR 2.9.3
