---
http_interactions:
- request:
    method: put
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/0
    body:
      encoding: UTF-8
      string: '[{"sku":"U-2662","externalId":"A88","description":"Super awesome description","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":0.1,"weight":0.1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0},"masterCase":{"individualItemsPerCase":1,"sku":"G-4034","description":"Techsche
        Remote Direct Amplifier","dimensions":{"length":1,"width":1,"height":1,"weight":1}},"inclusionRules":{"insertWhenWorthCurrency":"USD"},"classification":"marketingInsert"}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Mon, 08 Jun 2015 18:22:04 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.027204'
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '88'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":404,"message":"Product not found.","resourceLocation":null}'
    http_version: 
  recorded_at: Mon, 08 Jun 2015 18:22:04 GMT
recorded_with: VCR 2.9.3
