---
http_interactions:
- request:
    method: post
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products
    body:
      encoding: UTF-8
      string: '[{"sku":"U68","externalId":"F-6200","description":"Pont Input Transmitter","category":"OTHER","batteryConfiguration":"NOBATTERY","values":{"costValue":1,"retailValue":4},"dimensions":{"length":1,"width":1,"height":1,"weight":1},"flags":{"isPackagedReadyToShip":1,"isFragile":0,"isDangerous":0,"isPerishable":0,"isLiquid":0,"isMedia":0,"isAdult":0,"hasInnerPack":0,"hasMasterCase":0,"hasPallet":0},"virtualKitContent":[{"externalId":"TEST-PRODUCT","quantity":1},{"externalId":"TEST-PRODUCT2","quantity":1}],"classification":"virtualKit"}]'
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Thu, 18 Jun 2015 00:04:14 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.067047'
      X-Request-Id:
      - e9165ff1a7ad47645074e55ec1bd6300
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '334'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products?offset=0&limit=1","resource":{"offset":0,"total":1,"previous":null,"next":null,"items":[{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/virtualKits\/510000013","resource":{"id":510000013,"externalId":"F-6200","sku":"U68","creationDate":"2015-06-17T17:04:14-07:00","description":"Pont
        Input Transmitter","status":"instock","classification":"virtualKit","virtualKitContent":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/virtualKits\/510000013\/content?offset=0&limit=20"},"flags":{"resourceLocation":null}}}]}}'
    http_version: 
  recorded_at: Thu, 18 Jun 2015 00:04:14 GMT
recorded_with: VCR 2.9.3
