---
http_interactions:
- request:
    method: get
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/510000014
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:33 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.040420'
      X-Request-Id:
      - 8c036381d7f8f90d2b104352575ac97b
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '290'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":200,"message":"Successful","resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/virtualKits\/510000014","resource":{"id":510000014,"externalId":"F32","sku":"F-5977","creationDate":"2015-06-22T09:30:32-07:00","description":"Phunt
        Side Controller","status":"instock","classification":"virtualKit","virtualKitContent":{"resourceLocation":"https:\/\/api.beta.shipwire.com\/api\/v3\/products\/virtualKits\/510000014\/content?offset=0&limit=20"},"flags":{"resourceLocation":null}}}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:33 GMT
recorded_with: VCR 2.9.3
