---
http_interactions:
- request:
    method: get
    uri: https://david.freerksen%40groundctrl.com:gOg6maBr6E@api.beta.shipwire.com/api/v3/products/0
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Content-Type:
      - application/json
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
      User-Agent:
      - Ruby
  response:
    status:
      code: 404
      message: Not Found
    headers:
      Date:
      - Mon, 22 Jun 2015 16:30:29 GMT
      Server:
      - Apache
      X-Process-Time-Seconds:
      - '0.027530'
      X-Request-Id:
      - adc02ca635d90f6a04fd5a0ee873fb4b
      Vary:
      - Accept-Encoding
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      P3p:
      - policyref="/w3c/p3p.xml", CP="COM CNT INT NAV PUR STA UNI CAO DSP CUR o i
        OUR IND"
      Content-Length:
      - '88'
      Content-Type:
      - application/json
    body:
      encoding: UTF-8
      string: '{"status":404,"message":"Product not found.","resourceLocation":null}'
    http_version: 
  recorded_at: Mon, 22 Jun 2015 16:30:29 GMT
recorded_with: VCR 2.9.3
